# Generated by Django 4.2.6 on 2023-11-08 00:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_user_age_remove_user_dni_user_create_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
